[profile.default]
solc_version = "0.8.20"
evm_version = "cancun"
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
show_progress = true
optimizer_runs = 1_000_000

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
mainnet = "{$MAINNET_RPC_URL}"
testnet = "{$TESTNET_RPC_URL}"